# Generated by Django 4.2 on 2023-05-29 14:58

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(max_length=20, verbose_name='código')),
                ('diagnosis_description', models.CharField(max_length=200, verbose_name='descripción')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Diagnóstico médico',
                'verbose_name_plural': 'Diagnósticos médicos',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='cédula')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='fecha de ingreso')),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('edad', models.IntegerField(default=0, editable=False)),
                ('telefono', models.CharField(max_length=15, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('acompanante', models.CharField(blank=True, max_length=120, null=True, verbose_name='nombre del acompañante')),
                ('parentesco', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono_acompanante', models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono del acompañante')),
                ('ocupacion', models.CharField(choices=[('empleado', 'Empleado'), ('independiente', 'Independiente'), ('pensionado', 'Pensionado'), ('ama_casa', 'Ama de casa'), ('estudiante', 'Estudiante')], max_length=60, verbose_name='ocupación')),
                ('profesion', models.CharField(blank=True, max_length=120, null=True, verbose_name='profesión')),
                ('seguridad_social', models.CharField(max_length=240)),
                ('motivo_consulta', models.TextField(verbose_name='motivo de consulta')),
                ('cronologia_de_patologia', models.TextField(verbose_name='cronología de la patología')),
                ('actividad_fisica', models.BooleanField(default=False, verbose_name='actividad física')),
                ('tipo_actividad_fisica', models.CharField(blank=True, max_length=240, null=True, verbose_name='tipo de actividad física')),
                ('frecuencia_actividad_fisica', models.CharField(choices=[('diario', 'Diario'), ('menor_tres_veces_semana', 'Menos de 3 días por semana'), ('tres_veces_semana', '3 días por semana'), ('mayor_tres_veces_semana', 'Más de 3 días por semana'), ('una_vez_semana', 'Un día por semana'), ('no', 'No aplica')], default='no', max_length=60, verbose_name='frecuencia de la actividad física')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='conclusión')),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to=home.models.Patient.user_directory_path, verbose_name='Adjuntar documento')),
                ('diagnosiso', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.diagnosis', verbose_name='diagnóstico médico')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=120, verbose_name='nombre')),
                ('test_description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('subcategory', models.CharField(max_length=120, verbose_name='subcategoría')),
                ('result_type', models.CharField(choices=[('text', 'Campo tipo texto'), ('bool', 'Campo positivo o negativo')], default='bool', max_length=60, verbose_name='tipo de resultado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='categoría')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='resultado')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient', verbose_name='paciente')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.test')),
            ],
            options={
                'verbose_name': 'test de paciente',
                'verbose_name_plural': 'tests de pacientes',
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution_record', models.TextField(verbose_name='Evolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Evolución',
                'verbose_name_plural': 'Evoluciones',
            },
        ),
    ]
