# Generated by Django 4.2 on 2023-05-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('edad', models.IntegerField(default=0, editable=False)),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('acompanante', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre del acompañante')),
                ('parentesco', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono_acompanante', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono del acompañante')),
                ('ocupacion', models.CharField(choices=[('empleado', 'Empleado'), ('independiente', 'Independiente'), ('pensionado', 'Pensionado'), ('ama_casa', 'Ama de casa'), ('estudiante', 'Estudiante')], max_length=60, verbose_name='Ocupación')),
                ('profesion', models.CharField(blank=True, max_length=120, null=True, verbose_name='Profesión')),
                ('seguridad_social', models.CharField(max_length=240)),
                ('diagnostico_medico', models.TextField(verbose_name='Diagnóstico médico')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('cronologia_de_patologia', models.TextField(verbose_name='Cronología de la patología')),
                ('actividad_fisica', models.BooleanField(default=False, verbose_name='Actividad física')),
                ('tipo_actividad_fisica', models.CharField(blank=True, max_length=240, null=True, verbose_name='Tipo de actividad física')),
                ('frecuencia_actividad_fisica', models.CharField(choices=[('diario', 'Diario'), ('menor_tres_veces_semana', 'Menos de 3 días por semana'), ('tres_veces_semana', '3 días por semana'), ('mayor_tres_veces_semana', 'Más de 3 días por semana'), ('una_vez_semana', 'Un día por semana'), ('no', 'No aplica')], default='no', max_length=60, verbose_name='Frecuencia de la actividad física')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusión')),
                ('adjuntar_documento', models.FileField(upload_to='user_files')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('subcategoria', models.CharField(max_length=120)),
                ('tipo_resultado', models.CharField(choices=[('text', 'Campo tipo texto'), ('bool', 'Campo positivo o negativo')], default='bool', max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.test')),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolucion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
            ],
            options={
                'verbose_name': 'Evolución',
                'verbose_name_plural': 'Evoluciones',
            },
        ),
    ]
