# Generated by Django 4.2 on 2023-06-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_description',
            field=models.CharField(max_length=255, verbose_name='descripción'),
        ),
    ]
