# Generated by Django 4.2 on 2023-05-15 15:55

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Diagnóstico médico',
                'verbose_name_plural': 'Diagnósticos médicos',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='diagnostico_medico',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='adjuntar_documento',
            field=models.FileField(blank=True, null=True, upload_to=home.models.Paciente.user_directory_path),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='home.diagnostico', verbose_name='Diagnóstico médico'),
        ),
    ]
