# Generated by Django 4.2 on 2023-05-30 17:11

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_patient_diagnostico_patientdiagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='documento_adjunto',
        ),
        migrations.AlterField(
            model_name='evolution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del registro'),
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=home.models.AttachedFile.get_patient_directory_path, verbose_name='adjunar documento')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='fecha de adición')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient', verbose_name='paciente')),
            ],
        ),
    ]
