# Generated by Django 4.2 on 2023-05-30 18:02

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_patient_documento_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachedfile',
            options={'verbose_name': 'documento adjunto', 'verbose_name_plural': 'documentos adjuntos'},
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='name',
            field=models.CharField(default=None, editable=False, max_length=100, null=True, verbose_name='nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='attachedfile',
            name='file',
            field=models.FileField(upload_to=home.models.AttachedFile.get_patient_directory_path, verbose_name='documento'),
        ),
    ]
