# Generated by Django 4.2 on 2023-05-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_attachedfile_options_attachedfile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedfile',
            name='name',
        ),
    ]
