# Generated by Django 4.2 on 2023-06-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_attachedfile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachedfile',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
