# Generated by Django 4.2 on 2023-06-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_attachedfile_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfile',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patient', verbose_name='paciente'),
        ),
    ]
