# Generated by Django 4.2 on 2023-06-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_attachedfile_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedfile',
            name='name',
            field=models.CharField(default=None, editable=False, max_length=100, null=True, verbose_name='nombre del archivo'),
        ),
    ]
