# Generated by Django 4.2 on 2023-06-09 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_attachedfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patienttest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
    ]
