# Generated by Django 4.2 on 2023-06-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_diagnosis_created_at_patienttest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de adición'),
        ),
    ]
